### ISSUE TITLE
Self link and media link missing

### ISSUE THREAD

**Issue by robinjhector** [fsouza/fake-gcs-server#758]
Hello!

Whenever I use the Google storage java sdk to list blobs in a fake-gcs-server bucket, none of the blobs have their "self link" and "media link" populated. I'm assuming this is a bug?

**Comment by robinjhector** [comment]
I'm quite dependent on this feature in my code :) Having these links available in my tests would be awesome!

**Comment by fsouza** [comment]
> I'm quite dependent on this feature in my code :) Having the links available for verification in my tests would be awesome! The links themselfs could be totally fake or dead for my purposes. In other words, they don't have to work.

Hey, thanks for opening this issue. Do you know what they're usually set to? I can dig into the docs/run some real examples if not.

**Comment by robinjhector** [comment]
https://cloud.google.com/storage/docs/json_api/v1/objects

I believe `mediaLink` is usually the link to view an image or media object directly, eg. in browser. I think GCS serves the binary data with the correct content-type header, and the browser solves the rest.

SelfLink is the link to the object in the bucket, which, if I open it in a browser, will be downloaded.

**Comment by fsouza** [comment]
> I believe mediaLink is usually the link to view an image or media object directly, eg. in browser. I think GCS serves the binary data with the correct content-type header, and the browser solves the rest.

Ohh interesting. Does that mean that it is not set for all objects?

**Comment by Jerome1337** [comment]
I'm facing the same issue today. This is not a blocker for me but it would be a real plus if the `mediaLink` is provided

**Comment by andreoss** [comment]
Any update on this?

**Comment by rtrzebinski-usc** [comment]
Same issue here, please implement media link so it can be tested, thank you.

**Comment by manuteleco** [comment]
I have obviously encountered the same issue. Perhaps #1524 helps everyone here, as it helps me.

However, I've noticed a similar problem (missing attributes that lead to failures in certain client libraries) in the `acl` object response attribute. That attribute contains an array of JSON documents, which are also supposed to contain `etag`, `selfLink` and possibly other attributes that are currently missing. At least that led to errors with [this library][1], so watch out for that.

Even though I've hit that similar other error with `acl`, I didn't address it because I have implemented #1520 instead. For my current use case I don't need ACL information, so having `fake-gcs-server` respect the `projection` parameter was enough for the time being. But if you need ACL information (`projection=full`), you might still hit a similar error until the missing attributes are added for ACLs as well, kind of like #1524 does for the top level attributes in the object response.

[1]: https://crates.io/crates/google-cloud-storage
